FROM ros:melodic-ros-core-bionic

SHELL ["/bin/bash", "-c"]

RUN apt-get update
RUN apt-get install git -y
RUN mkdir -p catkin_ws/src
RUN apt-get install build-essential -y

WORKDIR /catkin_ws
RUN . /opt/ros/melodic/setup.sh && \
    catkin_make

WORKDIR /catkin_ws/src

RUN git clone https://github.com/KumarRobotics/vicon.git
WORKDIR /catkin_ws

RUN apt-get install libeigen3-dev -y
RUN apt install libyaml-cpp-dev -y
RUN apt-get install ros-melodic-tf2-ros -y
RUN apt-get install ros-melodic-tf -y

RUN . /opt/ros/melodic/setup.sh && \
    catkin_make
RUN sed -i "s|129|78|g" vicon/vicon/launch/vicon.launch

CMD /bin/bash
